export interface IPropsStar {
  id: string;
  starAmount?: number;
  minRandomTopAndLeft: number;
  maxRandomTopAndLeft: number;
  timeMinRandomAnimationDelay: number;
  timeMaxRandomAnimationDelay: number;
}

export interface IPropsStarValue {
  id: string;
  left: number;
  top: number;
  animationDelay: number;
  animationDuration: number;
  width?: number;
  height?: number;
  opacity?: number;
  background?: string;
}

export const propsStar: IPropsStar = {
  id: "Star1",
  starAmount: 3,
  minRandomTopAndLeft: 10,
  maxRandomTopAndLeft: 60,
  timeMinRandomAnimationDelay: 6,
  timeMaxRandomAnimationDelay: 11,
};

export const starValue: IPropsStarValue[] = [
  {
    id: "Star1",
    left: 10,
    top: 10,
    animationDelay: 5.4,
    animationDuration: 1.2,
    width: 3,
    height: 3,
    opacity: 0.7,
    background: "#BE6590",
  },
  {
    id: "Star2",
    left: 20,
    top: 60,
    animationDelay: 5.2,
    animationDuration: 1.3,
    width: 3,
    height: 3,
    opacity: 0.8,
    background: "#FE9C7F",
  },
  {
    id: "Star3",
    left: 25,
    top: 80,
    animationDelay: 5.4,
    animationDuration: 1.4,
    width: 3,
    height: 3,
    opacity: 0.7,
    background: "#FFC1A0",
  },
  {
    id: "Star4",
    left: 28,
    top: 70,
    animationDelay: 5.9,
    animationDuration: 1.5,
    width: 3,
    height: 3,
    opacity: 0.7,
    background: "#632B6C",
  },
  {
    id: "Star5",
    left: 40,
    top: 20,
    animationDelay: 6.2,
    animationDuration: 1.6,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star6",
    left: 60,
    top: 80,
    animationDelay: 6,
    animationDuration: 1.7,
    width: 3,
    height: 3,
    opacity: 1,
    background: "#ffffff",
  },
  {
    id: "Star7",
    left: 70,
    top: 30,
    animationDelay: 5.8,
    animationDuration: 1.2,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star8",
    left: 80,
    top: 70,
    animationDelay: 5.3,
    animationDuration: 1.3,
    width: 3,
    height: 3,
    opacity: 0.7,
    background: "#ffffff",
  },
  {
    id: "Star9",
    left: 90,
    top: 90,
    animationDelay: 6.2,
    animationDuration: 1.4,
    width: 4,
    height: 4,
    opacity: 0.9,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star10",
    left: 95,
    top: 10,
    animationDelay: 6,
    animationDuration: 1.5,
    width: 5,
    height: 5,
    opacity: 0.9,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star11",
    left: 98,
    top: 70,
    animationDelay: 6.2,
    animationDuration: 1.6,
    width: 3,
    height: 3,
    opacity: 0.7,
    background: "#ffffff",
  },
  {
    id: "Star12",
    left: 83,
    top: 80,
    animationDelay: 6.6,
    animationDuration: 1.2,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star13",
    left: 14,
    top: 77,
    animationDelay: 7,
    animationDuration: 2,
    width: 3,
    height: 3,
    opacity: 0.7,
    background: "#ffffff",
  },
  {
    id: "Star18",
    left: 31,
    top: 40,
    animationDelay: 5.1,
    animationDuration: 2.2,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star14",
    left: 63,
    top: 40,
    animationDelay: 7.4,
    animationDuration: 2.2,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star19",
    left: 73,
    top: 10,
    animationDelay: 6.4,
    animationDuration: 2.4,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star15",
    left: 83,
    top: 30,
    animationDelay: 6.6,
    animationDuration: 2.2,
    width: 3,
    height: 3,
    opacity: 0.7,
    background: "#632B6C",
  },
  {
    id: "Star16",
    left: 5,
    top: 30,
    animationDelay: 6.3,
    animationDuration: 3.2,
    background: "#ffffff",
  },
  {
    id: "Star20",
    left: 7,
    top: 35,
    animationDelay: 5.1,
    animationDuration: 2.8,
    width: 3,
    height: 3,
    opacity: 0.7,
    background: "#ffffff",
  },
  {
    id: "Star21",
    left: 11,
    top: 50,
    animationDelay: 6.1,
    animationDuration: 3,
    width: 5,
    height: 5,
    opacity: 0.8,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star17",
    left: 75,
    top: 50,
    animationDelay: 6.7,
    animationDuration: 3.2,
    width: 5,
    height: 5,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star22",
    left: 12,
    top: 40,
    animationDelay: 5.2,
    animationDuration: 2.2,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star23",
    left: 7,
    top: 40,
    animationDelay: 5.4,
    animationDuration: 2.6,
    width: 5,
    height: 5,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star24",
    left: 7,
    top: 80,
    animationDelay: 5,
    animationDuration: 3,
    width: 5,
    height: 5,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star41",
    left: 9,
    top: 70,
    animationDelay: 5.7,
    animationDuration: 2.7,
    width: 3,
    height: 3,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star42",
    left: 70,
    top: 65,
    animationDelay: 4.5,
    animationDuration: 2.4,
    width: 6,
    height: 6,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star43",
    left: 65,
    top: 70,
    animationDelay: 4.7,
    animationDuration: 2.8,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star38",
    left: 63,
    top: 63,
    animationDelay: 5.7,
    animationDuration: 3.2,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star25",
    left: 83,
    top: 63,
    animationDelay: 5.8,
    animationDuration: 3.4,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star39",
    left: 80,
    top: 53,
    animationDelay: 5.3,
    animationDuration: 1.2,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star26",
    left: 90,
    top: 45,
    animationDelay: 5.7,
    animationDuration: 1.7,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star27",
    left: 88,
    top: 35,
    animationDelay: 6.1,
    animationDuration: 1.3,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star40",
    left: 84,
    top: 15,
    animationDelay: 6.8,
    animationDuration: 2.5,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star28",
    left: 54,
    top: 16,
    animationDelay: 6,
    animationDuration: 2.2,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star29",
    left: 37,
    top: 9,
    animationDelay: 5.5,
    animationDuration: 3.2,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star30",
    left: 27,
    top: 12,
    animationDelay: 5.8,
    animationDuration: 3.6,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star31",
    left: 43,
    top: 43,
    animationDelay: 5.1,
    animationDuration: 4.2,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star32",
    left: 38,
    top: 55,
    animationDelay: 7,
    animationDuration: 3.1,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star33",
    left: 37,
    top: 69,
    animationDelay: 6.6,
    animationDuration: 3,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star34",
    left: 20,
    top: 20,
    animationDelay: 5.8,
    animationDuration: 4.2,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star35",
    left: 28,
    top: 28,
    animationDelay: 4.5,
    animationDuration: 5.2,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star36",
    left: 62,
    top: 28,
    animationDelay: 4.8,
    animationDuration: 1.2,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
  {
    id: "Star37",
    left: 62,
    top: 12,
    animationDelay: 5.1,
    animationDuration: 3.1,
    width: 4,
    height: 4,
    opacity: 1,
    background: "linear-gradient(-45deg, #5f91ff, rgba(0, 0, 255, 0))",
  },
];
